name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Lint all projects
        run: npm run lint

      - name: Build all projects
        run: npm run build:ci

      - name: Test ngx-dashboard (331 tests)
        run: |
          timeout 300 ng test ngx-dashboard --no-watch --browsers=ChromeHeadless --code-coverage

      - name: Test ngx-dashboard-widgets (86 tests)
        run: |
          timeout 300 ng test ngx-dashboard-widgets --no-watch --browsers=ChromeHeadless --code-coverage

      - name: Test demo (33 tests)
        run: |
          timeout 300 ng test demo --no-watch --browsers=ChromeHeadless --code-coverage

      - name: Security audit (BLOCKING)
        run: npm audit --audit-level=moderate
